- package.json
- webpack.config.js
- webpack.production.config.js
- `npm run build` does development build and `npm run build-prod` does production build
@ahilangopal
> Added production and dev web pack build configs

- sections/intro.php
- style.css
> removed hero avator

- frontend/components/video/index.js
- sections/intro.php
- style.css
Added Parallax to the Hero title
> Added Parallax to the Hero title

- assets/styles/intro.scss
- assets/styles/skills.scss
- functions.php
- inc/customizer/custom-css.php
- package.json
- style.css
> removed bootstrap - added simple grid

- assets/styles/helpers.scss
added mixins - margin and padding
> added helper mixin helpers

- inc/customizer/customizer.php
Main image key: `latte_about_avatar`
image1 Key: `latte_about_parallax_image1`
image2 Key: `latte_about_parallax_image2`
@ahilangopal
> about section three images settings

- assets/styles/base.scss
- assets/styles/color-variables.scss
- assets/styles/menu.scss
- assets/styles/typography.scss
- header.php
- style.css
- Removed old styles for the menu item
- new styles are added 
**Demo:**
@ahilangopal
> removed old style for the menu items

- assets/styles/base.scss
- assets/styles/circular-progress-bar.scss
- assets/styles/helpers.scss
- assets/styles/mixins/mediaQueries.scss
- assets/styles/services.scss
- assets/styles/skills.scss
- assets/styles/typography.scss
- assets/styles/video.scss
- frontend/modules/recentWorks/components/Services.js
- frontend/modules/recentWorks/components/serviceItem.js
- frontend/modules/skillsSection/index.js
- style.css
> responsive changes - added helpers

- assets/styles/base.scss
- assets/styles/hamburger-mobile-menu.scss
- frontend/components/hamburgerMenu/index.js
- frontend/entries/baseEntry/index.js
- frontend/entries/desktop/hamburgerMenuEntry.js
- header.php
- package.json
- only hamburger added 
- no action to show menu item yet
> hamburger added

- assets/styles/parallax-image.scss
- assets/styles/parallax-text-type1.scss
- assets/styles/services.scss
- assets/styles/skills.scss
- assets/styles/typography.scss
- assets/styles/video.scss
- frontend/modules/parllaxImageText/index.js
- frontend/modules/skillsSection/index.js
> Customs Changes

- assets/styles/hamburger-mobile-menu.scss
- assets/styles/menu.scss
- frontend/components/hamburgerMenu/index.js
- header.php
- finished implementation
@ahilangopal
> hamburger implementation

- assets/styles/circular-progress-bar.scss
- assets/styles/skills.scss
- frontend/modules/skillsSection/index.js
- fixed all skills spacing and responsiveness
> fixed skills section responsive

- assets/js/scripts.js
- assets/styles/services.scss
- frontend/modules/recentWorks/components/Services.js
- style.css
- removed unused css 
- made heights same for services card 
@ahilangopal
> Added same height for the services card boxes

- assets/styles/mixins/mediaQueries.scss
- assets/styles/video.scss
> intro responsive

- assets/styles/helpers.scss
- assets/styles/skills.scss
- assets/styles/typography.scss
- frontend/modules/recentWorks/components/Services.js
- frontend/modules/skillsSection/index.js
- fixed header spacing and fonts
> fixed section headers spacing and font size

- functions.php
- inc/customizer/customizer.php
- sections/intro.php
> added support for video format

- assets/styles/skills.scss
Fixed the opacity issue in mobile
> Fixed the opacity issue in mobile

- assets/styles/services.scss
- frontend/modules/recentWorks/components/serviceItem.js
> added width fix for service cards

- assets/styles/video.scss
- frontend/components/video/index.js
> video control option

- Gruntfile.js
- assets/styles/parallax-text-type1.scss
- frontend/entries/baseEntry/context.js
- frontend/entries/baseEntry/index.js
- frontend/modules/parllaxImageText/components/parllaxText.js
- frontend/modules/parllaxImageText/index.js
- package.json
- webpack.config.js
- webpack.dev.config.js
- webpack.production.config.js
> Discard parallax text in mobile breakpoints

- Gruntfile.js
- assets/styles/hamburger-mobile-menu.scss
- frontend/components/hamburgerMenu/index.js
- header.php
- package.json
- style.css
- Added Mobile Menu Animation
- Added the Mobile Click to Close
- Added Mobile Menu Stylings
- Added Grunt Clean
> - Added Grunt Clean

- assets/styles/hamburger-mobile-menu.scss
- assets/styles/services.scss
- frontend/components/hamburgerMenu/index.js
- style.css
- hamburger fixes
- services touch devices - disabled the z-transform
> hamburger fixes

- assets/styles/services.scss
- frontend/modules/recentWorks/components/Services.js
- frontend/modules/recentWorks/components/serviceItem.js
- style.css
> Fixed flex issue

- assets/styles/parallax-text-type1.scss
- frontend/modules/skillsSection/index.js
> -Skills Render Issue Fix

- assets/styles/skills.scss
- frontend/modules/skillsSection/index.js
Skill Section Loading Issue Fix
> Skill Section Loading Issue Fix
